name: Debug Issue Events
on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Issue Event
        run: |
          echo "=== ISSUE EVENT DEBUG ==="
          echo "Event action: ${{ github.event.action }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Label added: ${{ github.event.label.name }}"
          echo ""
          echo "=== ALL ISSUE LABELS ==="
          echo '${{ toJson(github.event.issue.labels) }}'
          echo ""
          echo "=== CONDITION CHECKS ==="
          echo "Has 'approved' label being added: ${{ contains(github.event.label.name, 'approved') }}"
          echo "Has 'data-submission' in existing labels: ${{ contains(github.event.issue.labels.*.name, 'data-submission') }}"
          echo "Combined condition result: ${{ contains(github.event.label.name, 'approved') && contains(github.event.issue.labels.*.name, 'data-submission') }}"
          echo ""
          echo "=== MAIN WORKFLOW TRIGGER CONDITIONS ==="
          echo "1. Event type 'labeled': ${{ github.event.action == 'labeled' }}"
          echo "2. Label name is 'approved': ${{ github.event.label.name == 'approved' }}"
          echo "3. Issue has 'data-submission' label: ${{ contains(github.event.issue.labels.*.name, 'data-submission') }}"
          echo ""
          echo "Should main workflow run? ${{ github.event.action == 'labeled' && github.event.label.name == 'approved' && contains(github.event.issue.labels.*.name, 'data-submission') }}"
